<?php

namespace Proxies\__CG__\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \UserBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'typeuser', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'adress', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'cin', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'tel', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'datenaiss', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'raisonsocial', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'horrairestravail', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'idtest'];
        }

        return ['__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'typeuser', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'adress', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'cin', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'tel', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'datenaiss', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'raisonsocial', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'horrairestravail', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\User' . "\0" . 'idtest'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeuser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeuser', []);

        return parent::getTypeuser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeuser($typeuser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeuser', [$typeuser]);

        return parent::setTypeuser($typeuser);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress($adress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaiss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaiss', []);

        return parent::getDatenaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaiss($datenaiss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaiss', [$datenaiss]);

        return parent::setDatenaiss($datenaiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonsocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonsocial', []);

        return parent::getRaisonsocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonsocial($raisonsocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonsocial', [$raisonsocial]);

        return parent::setRaisonsocial($raisonsocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorrairestravail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorrairestravail', []);

        return parent::getHorrairestravail();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorrairestravail($horrairestravail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorrairestravail', [$horrairestravail]);

        return parent::setHorrairestravail($horrairestravail);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtest', []);

        return parent::getIdtest();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtest($idtest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtest', [$idtest]);

        return parent::setIdtest($idtest);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
