moniteur_moniteur:
    resource: "@MoniteurBundle/Resources/config/routing/moniteur.yml"
    prefix:   /moniteur

moniteur_homepage:
    path:     /
    defaults: { _controller: MoniteurBundle:Default:index }
